language: node_js
node_js: 12
sudo: false
before_install:
    - if [ ! -e $HOME/conda/bin/activate ]; then
      wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
      bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
      fi
    - source $HOME/conda/bin/activate root
install:
    - conda env update -f environment.yml
    - pip install -r requirements.txt
    - jlpm
script:
    - pytest --cov=jupyterlab_thredds --cov-report xml --cov-report term --cov-branch
    - jlpm test
    - jlpm lint
    - jlpm build
cache:
    directories:
      - $HOME/.cache/pip
      - $HOME/conda
      - "node_modules"
    yarn: true
addons:
  sonarcloud:
    organization: ewatercycle
after_success:
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN
